version: 2
jobs:
  build:
    docker:
      - image: node:12.14.1

    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    steps:
      - checkout

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npx semantic-release

  lint:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm run lint

  test-integration:
    docker:
      - image: circleci/node:14.11.0-stretch
      # Integration tests need MongoDB server running and accessible on port 27017
      - image: circleci/mongo:4.2.0
        command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
        ports:
          - "27017:27017"
    steps:
      - checkout
      - run:
          name: Run Integration Tests
          environment:
            MONGO_URL: mongodb://localhost:27017/test
            MONGO_USE_UNIFIED_TOPOLOGY: false
          command: npx --quiet --package @reactioncommerce/ci-scripts@1.12.2 run-integration-tests

  test:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm run test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: reaction-publish-semantic-release
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - test-integration:
          requires:
            - build
      - deploy:
          context: reaction-publish-semantic-release
          requires:
            - lint
            - test
            - test-integration
          filters:
            branches:
              only: trunk
